// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cceoeyfaecbxoiwovent.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjZW9leWZhZWNieG9pd292ZW50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NTg5MTgsImV4cCI6MjA3NDQzNDkxOH0.CUbfpBFSDx0QGIyzdfENxDanUxpgutqsS7vlCI3QBp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});